name: "Deploy Hifi Docs to Firebase Hosting"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "20"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the packages"
        run: "yarn build"

      - name: "Deploy the Hifi Docs to Firebase Hosting"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: "live"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIFI_DOCS }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          projectId: "hifi-docs"
